//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fangwu
    {
        public int id { get; set; }
        public int FwNo { get; set; }
        public string ztbianhao { get; set; }
        public int TaNo { get; set; }
        public string Fwhtbh { get; set; }
        public string FwXzq { get; set; }
        public string FwFcqh { get; set; }
        public string FwFcfqh { get; set; }
        public string FwQh { get; set; }
        public string FwZhen { get; set; }
        public string FwStreet { get; set; }
        public string FwMphm { get; set; }
        public string FwMpfh { get; set; }
        public string FwYzbm { get; set; }
        public Nullable<byte> FwTxlb { get; set; }
        public Nullable<int> FwDxcs { get; set; }
        public Nullable<int> FwDscs { get; set; }
        public string FwJcnd { get; set; }
        public string Fwjg { get; set; }
        public string Fwyt { get; set; }
        public string Fwcb { get; set; }
        public string FwJzys { get; set; }
        public Nullable<float> FwJzmj { get; set; }
        public Nullable<float> FwGymj { get; set; }
        public Nullable<float> Fwtnmj { get; set; }
        public Nullable<float> Fwgtftmj { get; set; }
        public Nullable<float> FwFtxs { get; set; }
        public Nullable<int> FwHss { get; set; }
        public string FwCqr { get; set; }
        public string Fwbsm { get; set; }
        public string Fwqtms { get; set; }
        public string FwHuituren { get; set; }
        public Nullable<System.DateTime> FwTime { get; set; }
        public Nullable<int> Zzhuanghao { get; set; }
        public string Zzhuangming { get; set; }
        public Nullable<int> Zcengshu { get; set; }
        public Nullable<int> ZBiaozhuncs { get; set; }
        public Nullable<int> ZQishiceng { get; set; }
        public Nullable<int> ZZongzhiceng { get; set; }
        public Nullable<float> ZZongmj { get; set; }
        public Nullable<float> ZGongyoumj { get; set; }
        public Nullable<float> ZTaoneimj { get; set; }
        public Nullable<float> ZLoutimj { get; set; }
        public Nullable<float> ZYangtaimj { get; set; }
        public Nullable<int> ZHushishu { get; set; }
        public Nullable<int> ZDanyuanshu { get; set; }
        public string Fwdongming { get; set; }
        public string Fwchdw { get; set; }
        public string Fwkance { get; set; }
        public string Fwxiaodui { get; set; }
        public string Fwfuhei { get; set; }
        public Nullable<float> Fwpeitaomj { get; set; }
        public Nullable<float> Fwdulimj { get; set; }
        public Nullable<float> Zpeitaomj { get; set; }
        public Nullable<float> Zdulimj { get; set; }
        public Nullable<int> jiekou { get; set; }
        public Nullable<int> Fwhsbianhao { get; set; }
        public string Fwzanceshice { get; set; }
        public Nullable<System.DateTime> FwNewTime { get; set; }
        public string Fwybcq { get; set; }
        public string Fwshifouspf { get; set; }
        public string Danszlouceng { get; set; }
        public string Danszdanyuan { get; set; }
        public Nullable<float> tudimianji { get; set; }
        public Nullable<float> Ttudimianji { get; set; }
        public string dantizuoluo { get; set; }
        public string xingzhengqu { get; set; }
        public string dong { get; set; }
        public string nan { get; set; }
        public string xi { get; set; }
        public string bei { get; set; }
        public Nullable<float> gongyoumj { get; set; }
        public Nullable<float> Zhandimianji { get; set; }
        public string beizhu { get; set; }
        public string sheng { get; set; }
        public string shi { get; set; }
        public string xian { get; set; }
        public string cehuiyiqi { get; set; }
        public Nullable<System.DateTime> jiandingriqi { get; set; }
        public string yucehuitubianhao { get; set; }
        public string xinjianliyonghuitubianhao { get; set; }
        public Nullable<int> biangengcehui { get; set; }
        public string zongdidaima { get; set; }
    }
}
