//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class FenTan
    {
        public int Id { get; set; }
        public string Fwhtbh { get; set; }
        public Nullable<int> Fwno { get; set; }
        public Nullable<int> Tano { get; set; }
        public string Dongming { get; set; }
        public string biaozhuncm { get; set; }
        public string Quyuxz { get; set; }
        public string Suoshugnq { get; set; }
        public string Fentangnq { get; set; }
        public string fentanmingcheng { get; set; }
        public byte[] hebingmingcheng { get; set; }
        public Nullable<float> GTfentanmj { get; set; }
        public byte[] fentanmianjistr { get; set; }
        public string cantanmingcheng { get; set; }
        public byte[] taoneimianjidezucheng { get; set; }
        public Nullable<float> Fentangymj { get; set; }
        public byte[] taoneimianjijisuanshi { get; set; }
        public byte[] cantanmianjistr { get; set; }
        public string xishumingcheng { get; set; }
        public byte[] quanloufenmingcheng { get; set; }
        public Nullable<float> quanlouxishu { get; set; }
        public byte[] shangjimingcheng { get; set; }
        public byte[] shangjijisuanshi { get; set; }
        public Nullable<float> jieshouxishu { get; set; }
        public byte[] bencisuanshi { get; set; }
        public Nullable<float> Benftxishu { get; set; }
        public byte[] fentanmianjiheji { get; set; }
        public Nullable<int> jianjiebiaozhi { get; set; }
        public Nullable<int> Dulixiangxiak { get; set; }
        public Nullable<int> Xiangxiafeixiangsou { get; set; }
        public Nullable<int> ssbs { get; set; }
        public string ss { get; set; }
        public string lc { get; set; }
        public string Dulixx { get; set; }
        public string Ggptduli { get; set; }
        public string ggpeitaoduliming { get; set; }
        public string xxfxs { get; set; }
        public byte[] fentanzb { get; set; }
        public byte[] shangjisuanshishuxue { get; set; }
        public byte[] bencisuanshishishuxue { get; set; }
    }
}
