//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hushitsuchuan
    {
        public int Id { get; set; }
        public Nullable<int> Fwno { get; set; }
        public Nullable<int> Tano { get; set; }
        public Nullable<int> Lcno { get; set; }
        public Nullable<int> Hsno { get; set; }
        public byte[] Tsuchuan { get; set; }
        public byte[] Tsudxf { get; set; }
        public byte[] Tsuwmf { get; set; }
        public byte[] TsuTwmf { get; set; }
    }
}
