//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class HuShi
    {
        public int id { get; set; }
        public int LcNo { get; set; }
        public int HsNo { get; set; }
        public Nullable<int> Hstxly { get; set; }
        public string Hshao { get; set; }
        public string Hstufuhao { get; set; }
        public Nullable<int> Hssuozailc { get; set; }
        public string Hssuozaignq { get; set; }
        public Nullable<float> Hsmj { get; set; }
        public Nullable<float> Hstaoneimj { get; set; }
        public Nullable<float> Hsytmj { get; set; }
        public Nullable<float> Hsfentanmj { get; set; }
        public Nullable<float> Hsfentanxs { get; set; }
        public string Hssuozaidy { get; set; }
        public string Hschanquanr { get; set; }
        public string Hsyongtu { get; set; }
        public string Hschanbie { get; set; }
        public string Hschanquanzh { get; set; }
        public Nullable<int> Fwno { get; set; }
        public Nullable<int> Tano { get; set; }
        public string dongming { get; set; }
        public string Hsming { get; set; }
        public string ggdlming { get; set; }
        public Nullable<int> Ggptduli { get; set; }
        public byte[] Tsuchuan { get; set; }
        public byte[] gongshi { get; set; }
        public string Hsjiegou { get; set; }
        public string Loucengxsming { get; set; }
        public string hushixsming { get; set; }
        public string huxing { get; set; }
        public string fengqu { get; set; }
        public string changxiang { get; set; }
        public string dong { get; set; }
        public string nan { get; set; }
        public string xi { get; set; }
        public string bei { get; set; }
        public Nullable<float> biaogaocha { get; set; }
        public Nullable<int> zycengshu { get; set; }
        public Nullable<int> qscengshu { get; set; }
        public byte[] TsuTwmf { get; set; }
        public string beizhu { get; set; }
        public string oldtfh { get; set; }
        public Nullable<float> oldjzmj { get; set; }
        public Nullable<float> oldtnmj { get; set; }
        public Nullable<float> oldftmj { get; set; }
        public Nullable<float> oldxs { get; set; }
        public Nullable<int> biangengbiaozhi { get; set; }
        public string zongdidaima { get; set; }
        public Nullable<int> IsEmp { get; set; }
    }
}
