//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class LouCeng
    {
        public int id { get; set; }
        public int TaNo { get; set; }
        public int LcNo { get; set; }
        public Nullable<int> Zhuanghao { get; set; }
        public string biaozhuncm { get; set; }
        public Nullable<int> Biaozhunch { get; set; }
        public Nullable<int> Biaozhuncqsh { get; set; }
        public Nullable<int> Biaozhunczzh { get; set; }
        public Nullable<int> LcQh { get; set; }
        public Nullable<float> Zongmj { get; set; }
        public Nullable<float> Waiqiangmj { get; set; }
        public Nullable<float> Tjwallmj { get; set; }
        public Nullable<float> Gongyoumj { get; set; }
        public Nullable<float> Taoneimj { get; set; }
        public Nullable<float> Loutimj { get; set; }
        public Nullable<float> Yangtaimj { get; set; }
        public Nullable<int> Hushishu { get; set; }
        public Nullable<int> Danyuanshu { get; set; }
        public Nullable<int> Fwno { get; set; }
        public string loucengfwyt { get; set; }
        public string dongming { get; set; }
        public Nullable<float> peitaomj { get; set; }
        public Nullable<float> dulimj { get; set; }
        public byte[] Tsuchuan { get; set; }
        public string loucengfwgj { get; set; }
        public Nullable<int> loucengzongtu { get; set; }
        public Nullable<float> cenggongyoumj { get; set; }
        public byte[] Tsudxf { get; set; }
        public byte[] Tsuwmf { get; set; }
        public string beizhu { get; set; }
        public Nullable<float> tudimianji { get; set; }
    }
}
