//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuYu
    {
        public int id { get; set; }
        public Nullable<int> HsNo { get; set; }
        public int QyNo { get; set; }
        public Nullable<int> LcNo { get; set; }
        public string TsuquyuNo { get; set; }
        public Nullable<int> Quyuhao { get; set; }
        public Nullable<bool> Hsftqb { get; set; }
        public string Quyuxz { get; set; }
        public Nullable<float> Quyumj { get; set; }
        public Nullable<float> Ytquyuwallmj { get; set; }
        public Nullable<float> Quyumjxs { get; set; }
        public string Suoshuhs { get; set; }
        public string Suoshugnq { get; set; }
        public string Fentangnq { get; set; }
        public string Suoshudy { get; set; }
        public Nullable<int> Dulixx { get; set; }
        public Nullable<int> Fwno { get; set; }
        public Nullable<int> Tano { get; set; }
        public string dongming { get; set; }
        public string biaozhuncm { get; set; }
        public string ggpeitaoduliming { get; set; }
        public Nullable<int> Ggptduli { get; set; }
        public Nullable<int> xxfxs { get; set; }
        public byte[] Tsuchuan { get; set; }
        public byte[] gongshi { get; set; }
        public string loucengfentan { get; set; }
        public byte[] loucengftchuan { get; set; }
        public byte[] quyufenkuaitsu { get; set; }
        public Nullable<float> posx1 { get; set; }
        public Nullable<float> posy1 { get; set; }
        public Nullable<float> loucengfentanquanlou { get; set; }
        public Nullable<float> mianjibeishu { get; set; }
        public string fengqu { get; set; }
        public Nullable<float> biaogaocha { get; set; }
        public Nullable<int> zycengshu { get; set; }
        public Nullable<int> qscengshu { get; set; }
        public string Hsjiegou { get; set; }
        public string Hsyongtu { get; set; }
    }
}
